export interface Token {
    "__raw": string,
    "given_name": string,
    "family_name": string,
    "nickname": string,
    "name": string,
    "picture": string,
    "updated_at": string,
    "email": string,
    "email_verified": boolean,
    "iss": string,
    "aud": string,
    "iat": number,
    "exp": number,
    "sub": string,
    "sid": string,
    "nonce": string,
}